# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=1000)),
                ('price', models.CharField(max_length=1000)),
                ('building_details', models.CharField(max_length=2000)),
                ('rooms_available', models.CharField(max_length=50)),
                ('about_owner', models.CharField(max_length=2000)),
                ('nom', models.CharField(max_length=3)),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
