# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
