# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20180309_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='building_details',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='flat',
            name='nom',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flat',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
